### ISSUE TITLE
Design API and System

### ISSUE THREAD

**Issue by hilakista** [ob-vss-ss18/ppl-core#1]

**Comment by hilakista** [comment]
Ich hab das Wiki mal etwas strukturiert und für jeden Service eine Seite angelegt. Dort kommt dann ne Beschreibung der Aufgaben rein und die API dazu. @FlagChecker schau mal was dir noch dazu einfällt ich werd später noch weiter machen

**Comment by FlagChecker** [comment]
@hilakista Nein, ich hab nichts gemacht. Bis morgen früh werde ich aber versuchen die TO-DOs aus Stock, Customer und Reservation rauszukriegen.

**Comment by hilakista** [comment]
Ich schließe den Issue, unser Part ist ja getan.
