### ISSUE TITLE
Request changing Datastructure

### ISSUE THREAD

**Issue by Stamcor** [ob-vss-ss18/ppl-core#11]
Wir brauchen eine Entscheidung bezüglich der Persistenzierung des Preises. 
Nach unserer Vorstellung fällt dies in den Aufgabenbereich von Billing und Mailing, da in einer Rechnung ein konkreter Preis notwendig ist.
@hilakista , @obcode ist die Annahme korrekt?
LG Leasing

**Comment by obcode** [comment]
Wie ist denn der Ablauf? Leasing stellt alles zusammen und holt sich von der Preisberechnung den Preis? Dieser Preis wird mit den restliche Daten an Billing und Mailing übergeben?
Aber wird dann nicht der "Leasingvertrag" bei Leasing persistiert?
//cc @eca852

**Comment by hilakista** [comment]
Leasing macht eine Anfrage an PriceCalc, dieser soll eine Liste mit den berechneten Preisen der einzelnen Items sowie den Gesamtpreis (mit Angabe wo welcher Rabatt angewandt wurde). Diese Liste soll als Grundlage für die Rechnung dienen.
Eine mögliche Lösung wäre dass Billing und Mailing eine RechungsID erstellt welche dann bei Leasing zum entsprechenden Vorgang gespeichert wird, so könnte dann der Preis im nachhinein abgefragt werden.

**Comment by eca852** [comment]
Wie im Praktikum angesprochen, können wir die PDF-Dateien in Heroku nicht speichern. Dies bedeutet, dass die Rechnung jedes Mal neu gemacht werden soll. Wenn die dafür benötigten Daten schon bei Leasingsvertrag gespeichert sind, kann man die schon immer wieder abrufen und benutzen. Also da die Rechnungen jedes Mal neu gemacht werden, kann man auch den Preis jedes Mal berechnen. Eine Persistierung des Preises muss dann ja auch nicht unbedingt sein?!

**Comment by eca852** [comment]
Zu RechnungsID gibt es meiner Meinung nach ein Problem, wenn Mailing und Billing die generieren soll. Da wir bei uns keine Daten speichern, haben wir keinen Zugriff auf andere RechnungsIDs und dadurch können wir nicht weitere generieren, die sich garantiert von anderen unterscheiden. Es ist viel einfacher, diese auch bei Leasing zu generieren und dazu speichern und falls es als Rechnungsnummer auf die Rechnung stehen soll, uns die Nummer mitliefern.

**Comment by hilakista** [comment]
Laut erstem API Design speichert Billing&Mailing die Daten der einzelnen Rechnungen in der eigenen Datenbank um später abgefragt werden zu können. Leasing speichert nur den Leasingvorgang, also Items, Datum, ... aber keinen Preis (höchstens den Endpreis), und schon recht nicht wie dieser zustande kommt. Aber wie bereits gesagt mit den entsprechenden Teams direkt in Verbindung setzen und ggfs. API und das Wiki ändern.
