### ISSUE TITLE
PriceCalulator: Änderungen an der GraphQL-API

### ISSUE THREAD

**Issue by mountainflo** [ob-vss-ss18/ppl-core#12]
### Übermittlung unnötiger Objekte/Eigenschaften

Bei der bisherigen Spezifikation der GraphQL-API (https://github.com/ob-vss-ss18/ppl-core/wiki/PriceCalculator) werden Informationen bei den Items übermittelt, die nicht notwendig sind. **Neupreis** des Skis/Stocks und **Kondition** können auch direkt vom PriceCalulator-Service beim Stock-Service ermittelt werden.

### Anmerkung zur GraphlQL-API des Stock-Services

Aktuell ist es nicht ersichtlich, ob Ski und Stöcke jeweils eine eigene ID besitzen oder es eine einheitliche ID über alle Objekttypen gibt. Es wäre sinnvoll, dass ein Objekt nicht nur gemeinsam mit ID und Typ identifizierbar ist. 

API siehe: https://github.com/ob-vss-ss18/ppl-core/wiki/Stock

**Eine ID alleine sollte zur Identifizierung aller unterschiedlicher Typen (Ski, Stock,...) ausreichend sein.**

**Comment by obcode** [comment]
@mountainflo bitte selbst im Wiki anpassen. Sie sollten Schreibrechte haben und können die unnötigen Daten selbst entfernen. Bitte dann auch beteiligte Kommunikationspartner cc setzen

Im Moment vergibt der Armin Harlos getrennte IDs, bzw. die die mit 1 anfangen sind Ski usw.
Einheitliche ID würde ich auch preferieren.

**Comment by hilakista** [comment]
Die anfängliche Idee war, da der Leasing Service bereits die nötigen Daten von Stock abgefragt hat, diese direkt an den PriceCalc weiterzugeben. Natürlich könnt ihr auch zusätzliche Calls an Stock machen, nur geht hierbei ja immer noch ein Call zu Auth einher was eben einen Overhead mit sich bringt.

Bzgl. der Vorgehensweise und auch den IDs bei Stock bitte direkt mit den Teams in Verbindung setzen und dann das Wiki anpassen.

**Comment by mountainflo** [comment]
Ok. Vielen Dank. Wir setzen uns mit den betroffenen Teams in Verbindung.
