### ISSUE TITLE
Funktion Verleih

### ISSUE THREAD

**Issue by hilakista** [ob-vss-ss18/ppl-core#2]
Welche Funktion hat das Modul Verleih bzw. was ist der Unterschied zwischen Verleih und Leasing?

**Comment by hilakista** [comment]
Also könnte man theoretisch den Verleih mit dem Leasing zusammenlegen, und aus dem alten Verleihsystem einen Auth Service für die Authentifikation für Verleih/Leasing und Reservierung machen? Das würde nämlich noch fehlen wenn man die Möglichkeit der Reservierung für Kunden von zu Hause einräumt.

**Comment by obcode** [comment]
Ja, klar. Das könnten wir machen.

Unterschied wäre dann ja nur:

- **Leasing**: diverse Rabatte, Dauer immer "die Saison" (=> Abgabe bis spätestens 30.04.)
- **Verleih**: keine Rabatte oder kostenlos (für zwei Tage weil "Zuckerl" beim Leasing), feste Dauer

**Comment by obcode** [comment]
Wenn die Gruppe das macht, soll sie bitte das Repo umbenennen in `ppl-auth`. Kann ich aber dann natürlich auch machen.
// cc: @MarEliSeg

**Comment by MarEliSeg** [comment]
Alles klar, dann machen wir einen Auth Service :thumbsup:

**Comment by obcode** [comment]
@MarEliSeg 
Ich finde, dass Passwordless Authentication für diesen Anwendungsfall auch einen gewissen Charme hat.

# Ablauf

1. Benutzer geht auf Website und gibt seine E-Mail-Adresse ein.
2. E-Mail-Adresse wird in der Kundenverwaltung gesucht.
3. Wenn 2. erfolgreich war, wird ein One-Time-Token mit einer gewissen Gültigkeitsdauer (z.B. 30 Minuten) generiert.
4. Token wird in der DB mit Gültigkeitszeitraum gespeichert.
5. Benutzer bekommt an die E-Mail-Adresse eine E-Mail mit einer URL in der das Token und die E-Mail-Adresse enthalten ist.
6. Über URL ist er Authentifiziert.

Es gibt dazu eine Implementierung in node.js/express unter https://passwordless.net/.

Darüber können sich natürlich auch Neukunden registrieren.

**Comment by MarEliSeg** [comment]
@obcode 
Für den Kunden ist das eine schöne Lösung. Man braucht dann aber eine zweite Variante für die Mitarbeiter, oder? Da die ja mehr Funktionen haben und nicht ständig ausgeloggt werden sollten.
