### ISSUE TITLE
Pre-Release 1

### ISSUE THREAD

**Issue by hilakista** [ob-vss-ss18/ppl-core#3]
Habe im ppl-core wiki einen Eintrag mit dem Anforderungen an das erste Release angelegt, und in den nicht-fertigen Repos einen Issue angelegt und den Eintrag dort verlinkt. Jedoch kann ich diesen Issue niemanden zuweisen, da ich kein Mitglied des Repos bin, und bin mir nun nicht sicher ob die zuständigen Ansprechpartner eine Email für den Issue bekommen.

Können Sie die Issues den jeweiligen Ansprechpartner zuweisen?

**Comment by hilakista** [comment]
Wahlweise können Sie mich auch den andern Repos zuweisen, dann kann ich zukünftige Issues selber zuweisen.

**Comment by obcode** [comment]
@hilakista Ich habe ein [Core-Team](https://github.com/orgs/ob-vss-ss18/teams/ppl-core) angelegt, dass in allen ppl-*-Repos Schreibrechte hat. Probieren Sie mal ob es so passt.

**Comment by markuskr97** [comment]
sollte funktionieren, wie vorgegeben

**Comment by markuskr97** [comment]
Falls nachgeprüft, bitte Issue schließen

**Comment by hilakista** [comment]
Der Client laeuft lokak und zusaetzlich auf Heroku, alle Services geben ein Hello World zurueck.

**Comment by obcode** [comment]
Bitte noch Folgendes (kopiert von https://ob.cs.hm.edu/public/vss/exercises/Leistungsnachweis.pdf) machen:
Die zwei Pre-Releases und das abschließende üRelease wird auch im Repository des Core-Teams getagged. Dazu werden alle anderen Repositories dort als Submodule eingebunden.

Vielleicht taggen wir auch in allen anderen Repos!?!

Wenn Sie Hilfe brauchen oder nicht verstehen was ich meine, einfach Bescheid sagen.

**Comment by hilakista** [comment]
Habe einen Wiki Eintrag erstellt (https://github.com/ob-vss-ss18/ppl-core/wiki/Release-Management) und in den Repos Issues dazu angelegt. Wenn diese durchgeführt sind erstelle ich im core repo den release Brach mit Tag.

**Comment by obcode** [comment]
Issues:
- ob-vss-ss18/ppl-customer#18
- ob-vss-ss18/ppl-client#10
- ob-vss-ss18/ppl-billingandmailing#7
- ob-vss-ss18/ppl-stock#31
- ob-vss-ss18/ppl-auth#4
- ob-vss-ss18/ppl-pricecalculator#6
- ob-vss-ss18/ppl-leasing#22
- ob-vss-ss18/ppl-reservation#9
